name: Run AutoLike

on:
#  schedule:
#    - cron: '40 6 * * 1-5' #!Исправить после теста.
#    - cron: '50 6 * * 1-5' #!Исправить после теста.
#    - cron: '0 7 * * 1-5' #!Исправить после теста.
#    - cron: '10 7 * * 1-5' #!Исправить после теста.
#    - cron: '20 7 * * 1-5' #!Исправить после теста.
  workflow_dispatch:
  repository_dispatch:
    types: [Scheduled-run-from-cronjob]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: Set up Python with retry
        run: |
          i=1
          until python --version 2>/dev/null | grep "3.11.3" || [ $i -gt 5 ]; do
            echo "Retrying setup-python... Attempt $i"
            i=$((i+1))
            sleep 60
            rm -rf /opt/hostedtoolcache/Python/3.11.3* || true
            curl -s https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json | grep "3.11.3" || continue
            sudo apt update && sudo apt install -y python3.11 python3.11-venv python3.11-dev
          done

          if ! python --version 2>/dev/null | grep "3.11.3"; then
            echo "Failed to install Python 3.11.3 after 5 attempts"
            exit 1
          fi
      
      - name: Cache Python packages
        uses: actions/cache@v3
        with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
            restore-keys: |
                ${{ runner.os }}-pip-    

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          api_id: ${{ secrets.API_ID }}
          api_hash: ${{ secrets.API_HASH }}
          chat_id: ${{ secrets.CHAT_ID }}
          user_id: ${{ secrets.USER_ID }}
        run: python bot.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 